### PR TITLE
#439 Fix not accepted course groupings showing in search result 

### PR DESCRIPTION
**Pull request by Ghaith-Chrit**
This PR closes: #439

### CODE REVIEW

**Review by JamesPartsafas — COMMENTED** [review]
I'm not sure this will work, because recall there might be multiple accepted versions of a grouping (the old versions are still marked as accepted) and it seems they'd still be included in this query, wouldn't they? If you added in your test method a third grouping that's accepted with version = 2, I think your test would fail.

**Comment by Ghaith-Chrit** [comment]
> I'm not sure this will work, because recall there might be multiple accepted versions of a grouping (the old versions are still marked as accepted) and it seems they'd still be included in this query, wouldn't they? If you added in your test method a third grouping that's accepted with version = 2, I think your test would fail.

Yes, but the controller is expected to return a list of course groupings so I thought we have to return all the accepted ones. Unless you want to return only the currently published one?

**Comment by JamesPartsafas** [comment]
> > I'm not sure this will work, because recall there might be multiple accepted versions of a grouping (the old versions are still marked as accepted) and it seems they'd still be included in this query, wouldn't they? If you added in your test method a third grouping that's accepted with version = 2, I think your test would fail.
> 
> Yes, but the controller is expected to return a list of course groupings so I thought we have to return all the accepted ones. Unless you want to return only the currently published one? In that case, I could just check the published attribute and get the lastest version.

We'd want a list of 10 groupings, but only the most recent accepted version of each grouping (not all the accepted versions). You should be able to use a very similar query to this one to achieve it https://github.com/JamesPartsafas/ConcordiaCurriculumManager/blob/1801bebe74acb7c3b5b26d1f9fe2116ea0ee537a/Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs#L76

**Comment by Ghaith-Chrit** [comment]
> not all the accepted versions

Is this for `GetCourseGroupingsBySchool` as well? In that case, why was it returning a list if it getting only the most recently accepted course grouping for a school?

**Review by JamesPartsafas — APPROVED** [review]

**Pull request merged**
