### PR TITLE
Implement frontend for deleting review messages

### LINKED ISSUE #548: Implement frontend for deleting review messages
Given I am a reviewer, when posting comments, I want to be able to delete those comments, in order to remove unwanted feedback.

This is a subtask of https://github.com/JamesPartsafas/ConcordiaCurriculumManager/issues/542

[Story Points: 4]
[Priority: Medium]
[Risk: Low]

Demo steps:
Given I'm a reviewer assigned to a dossier,
Submit a review message.
Then, click delete on the message and confirm the message deletion.
The message will be removed with a note displaying that the message was removed.

### PR DESCRIPTION
**Pull request by kennyphan100**
Created a new Delete button to remove the unwanted messages.

This closes #548

### CODE REVIEW

**Comment by kennyphan100** [comment]
I'm not sure why my branch removed some new code for the Voting functionality. Ill fix that.

**Comment by kennyphan100** [comment]
> I'm not sure why my branch removed some new code for the Voting functionality. I'll fix that.

It should be good now.

**Comment by JamesPartsafas** [comment]
It hides the comment, but if there's any replies, all the replies get removed as well, because of our nested comment system. Instead, we can use a system similar to Reddit, where if a user deletes their message, the system simply displays `This message has been deleted.`, and any replies are still shown (in fact, this is why `isDeleted` is a boolean value for message now).

**Comment by kennyphan100** [comment]
> It hides the comment, but if there's any replies, all the replies get removed as well, because of our nested comment system. Instead, we can use a system similar to Reddit, where if a user deletes their message, the system simply displays `This message has been deleted.`, and any replies are still shown (in fact, this is why `isDeleted` is a boolean value for message now).

I made the changes. Let me know what you think.

**Review by JamesPartsafas — APPROVED** [review]

**Pull request merged**
