### PR TITLE
Homepage and Navbar modifications

### PR DESCRIPTION
**Pull request by Dinferno-lol**
Changes the navbar to use proper buttons and spacing, adds a proper looking home page with a functional link to the dossiers page.
closes: #110 
Relates to #9

### CODE REVIEW

**Comment by AgnesCroteau** [comment]
Not responsive to screen sizes changes, will look into it tomorrow.
image

**Comment by JamesPartsafas** [comment]
It looks good but you may want to only display the view dossiers and view groups buttons if the user is logged in. If they're not logged in, there should be buttons to sign in and register. If the user should only be able to access the home page if they're logged in, there should be a check in place in the App.tsx file to block the unauthenticated user from accessing the homepage (and redirecting to the login page).

**Comment by Dinferno-lol** [comment]
> It looks good but you may want to only display the view dossiers and view groups buttons if the user is logged in. If they're not logged in, there should be buttons to sign in and register. If instead the user should only be able to access the home page if they're logged in (I can't quite remember what was decided upon for the UI in our discussion on this), there should be a check in place in the App.tsx file to block the unauthenticated user from accessing the homepage (and redirecting to the login page).

Thanks for the reminder, I thought I made this change in App.tsx, must have been on a different branch.

**Review by JamesPartsafas — APPROVED** [review]
LGTM

**Pull request merged**
