### PR TITLE
Overflow fixes #282

### LINKED ISSUE #282: Overflow fixes
As a logged-in user, I want the number of groups to be displayed in a way that prevents overflow on the page, so that I can easily navigate and comprehend the information without excessive scrolling or visual clutter.

[Story Points: 3]
[Priority: Low]
[Risk: Low]

Demo steps:
Given I’m logged-in
When I navigate to the groups page, the groups are displayed correctly
Then, I can easily navigate between groups.

### PR DESCRIPTION
**Pull request by eyadsw**
closes #282

### CODE REVIEW

**Comment by JamesPartsafas** [comment]
The overflow seems fixed and the pagination is good, and the new UI looks nice, good work there, but there's 2 concerns:
1: There seems to be misalignment issues in the groups table (which is an issue since the default groups will be misaligned)
2: You seem to have removed all the buttons to manage the group members and masters, which were completed features and important to the site. Did you intend to move these elsewhere?

image

**Comment by JamesPartsafas** [comment]
For reference, these were all the columns available before: 
image

**Comment by eyadsw** [comment]
yea I'm aware of that. I focused on the overflow in this pull request but I fixed that in the edit/delete groups.

manage

**Review by JamesPartsafas — APPROVED** [review]
Okay just make sure to merge the edit/delete group pr as soon as you can.

**Pull request merged**
